In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import re
from bs4 import BeautifulSoup
import time

In [6]:
URL = "https://www.nykaa.com/bath-body/body-care/body-lotions-moisturizers/c/371?search_redirection=True"

In [8]:
page=requests.get(URL)

In [9]:
page.status_code

200

In [10]:
page = requests.get(URL)
page_content = page.text
soup = BeautifulSoup(page_content)

In [11]:
Product_Name = []
Price = []
SellingPrice=[]
Discount=[]
RatingCount = []
for i in range(1, 50):
    print('-------------------------------------------------------')
    start = time.time()
    URL = "https://www.nykaa.com/bath-body/body-care/body-lotions-moisturizers/c/371?search_redirection=True".format(i)
    page = requests.get(URL)
    page_content = page.text
    soup = BeautifulSoup(page_content)
    #print(soup.text)
    for x in soup.find_all('div', attrs ={'class':"css-ifdzs8"}):
        PName = x.find('div', attrs = {'class': "css-xrzmfa"})
        Price1 = x.find('span', attrs = {'class': 'css-17x46n5'})
        Selling1 = x.find('span', attrs = {'class': 'css-111z9ua'})
        Discount1 = x.find('span', attrs = {'class': 'css-cjd9an'})
        Rating1 = x.find('span', attrs = {'class': "css-1qbvrhp"})
        Volume1 = x.find('span', attrs = {'class': "css-1ctpgu6"})
        if PName is None:
            Product_Name.append(np.nan)
        else:
            Product_Name.append(PName.text)
            
        if Price1 is None:
            Price.append(np.nan)
        else:
            Price.append(Price1.text)
            
        if Selling1 is None:
            SellingPrice.append(np.nan)
        else:
            SellingPrice.append(Selling1.text)
            
        if Discount1 is None:
            Discount.append(np.nan)
        else:
            Discount.append(Discount1.text)
            
        if Rating1 is None:
            RatingCount.append(np.nan)
        else:
            RatingCount.append(Rating1.text)
                
        
    end = time.time()
    print("Page {} is completed in {} seconds".format(i, end-start))

-------------------------------------------------------
Page 1 is completed in 0.11722397804260254 seconds
-------------------------------------------------------
Page 2 is completed in 0.08606624603271484 seconds
-------------------------------------------------------
Page 3 is completed in 0.09556984901428223 seconds
-------------------------------------------------------
Page 4 is completed in 0.08146262168884277 seconds
-------------------------------------------------------
Page 5 is completed in 0.08103513717651367 seconds
-------------------------------------------------------
Page 6 is completed in 0.09963035583496094 seconds
-------------------------------------------------------
Page 7 is completed in 0.0818936824798584 seconds
-------------------------------------------------------
Page 8 is completed in 0.0952150821685791 seconds
-------------------------------------------------------
Page 9 is completed in 0.09069371223449707 seconds
-------------------------------------------------------
Page 10 is completed in 0.08114123344421387 seconds
-------------------------------------------------------
Page 11 is completed in 0.07633709907531738 seconds
-------------------------------------------------------
Page 12 is completed in 0.0883026123046875 seconds
-------------------------------------------------------
Page 13 is completed in 0.08965802192687988 seconds
-------------------------------------------------------
Page 14 is completed in 0.08276104927062988 seconds
-------------------------------------------------------
Page 15 is completed in 0.0830373764038086 seconds
-------------------------------------------------------
Page 16 is completed in 0.07809209823608398 seconds
-------------------------------------------------------
Page 17 is completed in 0.07971453666687012 seconds
-------------------------------------------------------
Page 18 is completed in 0.09265518188476562 seconds
-------------------------------------------------------
Page 19 is completed in 0.08495688438415527 seconds
-------------------------------------------------------
Page 20 is completed in 0.09769082069396973 seconds
-------------------------------------------------------
Page 21 is completed in 0.08733582496643066 seconds
-------------------------------------------------------
Page 22 is completed in 0.07915115356445312 seconds
-------------------------------------------------------
Page 23 is completed in 0.08077526092529297 seconds
-------------------------------------------------------
Page 24 is completed in 0.08487319946289062 seconds
-------------------------------------------------------
Page 25 is completed in 0.09874463081359863 seconds
-------------------------------------------------------
Page 26 is completed in 0.10709738731384277 seconds
-------------------------------------------------------
Page 27 is completed in 0.07887935638427734 seconds
-------------------------------------------------------
Page 28 is completed in 0.0773463249206543 seconds
-------------------------------------------------------
Page 29 is completed in 0.2668459415435791 seconds
-------------------------------------------------------
Page 30 is completed in 0.08838534355163574 seconds
-------------------------------------------------------
Page 31 is completed in 0.08006000518798828 seconds
-------------------------------------------------------
Page 32 is completed in 0.1004643440246582 seconds
-------------------------------------------------------
Page 33 is completed in 0.0820932388305664 seconds
-------------------------------------------------------
Page 34 is completed in 0.09720730781555176 seconds
-------------------------------------------------------
Page 35 is completed in 0.10399103164672852 seconds
-------------------------------------------------------
Page 36 is completed in 0.07819938659667969 seconds
-------------------------------------------------------
Page 37 is completed in 0.08844280242919922 seconds
-------------------------------------------------------
Page 38 is completed in 0.08556151390075684 seconds
-------------------------------------------------------
Page 39 is completed in 0.08922505378723145 seconds
-------------------------------------------------------
Page 40 is completed in 0.08959221839904785 seconds
-------------------------------------------------------
Page 41 is completed in 0.0964975357055664 seconds
-------------------------------------------------------
Page 42 is completed in 0.10284566879272461 seconds
-------------------------------------------------------
Page 43 is completed in 0.09790229797363281 seconds
-------------------------------------------------------
Page 44 is completed in 0.08322834968566895 seconds
-------------------------------------------------------
Page 45 is completed in 0.08102130889892578 seconds
-------------------------------------------------------
Page 46 is completed in 0.07909178733825684 seconds
-------------------------------------------------------
Page 47 is completed in 0.08428788185119629 seconds
-------------------------------------------------------
Page 48 is completed in 0.09736776351928711 seconds
-------------------------------------------------------
Page 49 is completed in 0.09633898735046387 seconds

In [12]:
data = {'ProductName':Product_Name, 'Price':Price, 'SellingPrice':SellingPrice, 'Discount':Discount,'RatingCount':RatingCount}
df= pd.DataFrame(data)

In [13]:
df

,ProductName,Price,SellingPrice,Discount,RatingCount
0,Vaseline Gluta-Hya Dewy Radiance Lotion Bright...,₹380,₹285,25% Off,( 22592 )
1,NIVEA Deep Moisture Serum Vit E Body Lotion 72...,₹760,₹532,30% Off,( 63469 )
2,Wishcare Sunscreen Body Lotion SPF 50 Broad Sp...,₹499,₹399,20% Off,( 18672 )
3,Plum BodyLovin' Vanilla Caramello Bestselling ...,₹495,₹396,20% Off,( 13983 )
4,Be Bodywise Pigmentation Removal Cream With 2....,₹649,₹549,15% Off,( 3435 )
...,...,...,...,...,...
975,Nykaa Wanderlust English Country Rose Floral B...,₹550,₹358,35% Off,( 54055 )
976,NIVEA Deep Moisture Serum Vit E Body Lotion 48...,₹760,₹532,30% Off,( 63469 )
977,"Vaseline Sun Protect SPF 30 Body Lotion, Reduc...",₹870,₹479,45% Off,( 17248 )
978,Cetaphil DailyAdvance Ultra Hydrating Lotion,₹279,₹240,14% Off,( 69661 )
979,Plum BodyLovin' Vanilla Caramello Bestselling ...,₹495,₹396,20% Off,( 13983 )

In [30]:
df['Brand'] = df['ProductName'].str.split().str[0]

In [31]:
df

,ProductName,Price,SellingPrice,Discount,RatingCount,Savings,PriceCategory,Brand
0,Vaseline Gluta-Hya Dewy Radiance Lotion Bright...,380.0,285,25.0,( 22592 ),95.0,Budget,Vaseline
1,NIVEA Deep Moisture Serum Vit E Body Lotion 72...,760.0,532,30.0,( 63469 ),228.0,Mid-range,NIVEA
2,Wishcare Sunscreen Body Lotion SPF 50 Broad Sp...,499.0,399,20.0,( 18672 ),100.0,Budget,Wishcare
3,Plum BodyLovin' Vanilla Caramello Bestselling ...,495.0,396,20.0,( 13983 ),99.0,Budget,Plum
4,Be Bodywise Pigmentation Removal Cream With 2....,649.0,549,15.0,( 3435 ),100.0,Mid-range,Be
...,...,...,...,...,...,...,...,...
975,Nykaa Wanderlust English Country Rose Floral B...,550.0,358,35.0,( 54055 ),192.0,Mid-range,Nykaa
976,NIVEA Deep Moisture Serum Vit E Body Lotion 48...,760.0,532,30.0,( 63469 ),228.0,Mid-range,NIVEA
977,"Vaseline Sun Protect SPF 30 Body Lotion, Reduc...",870.0,479,45.0,( 17248 ),391.0,Mid-range,Vaseline
978,Cetaphil DailyAdvance Ultra Hydrating Lotion,279.0,240,14.0,( 69661 ),39.0,Budget,Cetaphil
979,Plum BodyLovin' Vanilla Caramello Bestselling ...,495.0,396,20.0,( 13983 ),99.0,Budget,Plum

In [14]:
df["Price"] = (df["Price"].str.replace(r'[^0-9.]', '', regex=True))
df["Price"] = pd.to_numeric(df["Price"], errors="coerce")

In [15]:
df

,ProductName,Price,SellingPrice,Discount,RatingCount
0,Vaseline Gluta-Hya Dewy Radiance Lotion Bright...,380.0,₹285,25% Off,( 22592 )
1,NIVEA Deep Moisture Serum Vit E Body Lotion 72...,760.0,₹532,30% Off,( 63469 )
2,Wishcare Sunscreen Body Lotion SPF 50 Broad Sp...,499.0,₹399,20% Off,( 18672 )
3,Plum BodyLovin' Vanilla Caramello Bestselling ...,495.0,₹396,20% Off,( 13983 )
4,Be Bodywise Pigmentation Removal Cream With 2....,649.0,₹549,15% Off,( 3435 )
...,...,...,...,...,...
975,Nykaa Wanderlust English Country Rose Floral B...,550.0,₹358,35% Off,( 54055 )
976,NIVEA Deep Moisture Serum Vit E Body Lotion 48...,760.0,₹532,30% Off,( 63469 )
977,"Vaseline Sun Protect SPF 30 Body Lotion, Reduc...",870.0,₹479,45% Off,( 17248 )
978,Cetaphil DailyAdvance Ultra Hydrating Lotion,279.0,₹240,14% Off,( 69661 )
979,Plum BodyLovin' Vanilla Caramello Bestselling ...,495.0,₹396,20% Off,( 13983 )

In [16]:
df["SellingPrice"] = (df["SellingPrice"].astype(str).str.replace(r'[^0-9.]', '', regex=True))
df["SellingPrice"] = pd.to_numeric(df["SellingPrice"], errors="coerce")

df["Discount"] = (df["Discount"].astype(str).str.replace(r'[^0-9.]', '', regex=True))
df["Discount"] = pd.to_numeric(df["Discount"], errors="coerce")

In [17]:
df

,ProductName,Price,SellingPrice,Discount,RatingCount
0,Vaseline Gluta-Hya Dewy Radiance Lotion Bright...,380.0,285,25.0,( 22592 )
1,NIVEA Deep Moisture Serum Vit E Body Lotion 72...,760.0,532,30.0,( 63469 )
2,Wishcare Sunscreen Body Lotion SPF 50 Broad Sp...,499.0,399,20.0,( 18672 )
3,Plum BodyLovin' Vanilla Caramello Bestselling ...,495.0,396,20.0,( 13983 )
4,Be Bodywise Pigmentation Removal Cream With 2....,649.0,549,15.0,( 3435 )
...,...,...,...,...,...
975,Nykaa Wanderlust English Country Rose Floral B...,550.0,358,35.0,( 54055 )
976,NIVEA Deep Moisture Serum Vit E Body Lotion 48...,760.0,532,30.0,( 63469 )
977,"Vaseline Sun Protect SPF 30 Body Lotion, Reduc...",870.0,479,45.0,( 17248 )
978,Cetaphil DailyAdvance Ultra Hydrating Lotion,279.0,240,14.0,( 69661 )
979,Plum BodyLovin' Vanilla Caramello Bestselling ...,495.0,396,20.0,( 13983 )

In [45]:
df["Savings"] = df["Price"] - df["SellingPrice"]
df["PriceCategory"] = pd.cut(df["Price"],bins=[0, 500, 1000,1200],labels=["Budget", "Mid-range", "Premium"])

In [25]:
df

,ProductName,Price,SellingPrice,Discount,RatingCount,Savings,PriceCategory
0,Vaseline Gluta-Hya Dewy Radiance Lotion Bright...,380.0,285,25.0,( 22592 ),95.0,Budget
1,NIVEA Deep Moisture Serum Vit E Body Lotion 72...,760.0,532,30.0,( 63469 ),228.0,Mid-range
2,Wishcare Sunscreen Body Lotion SPF 50 Broad Sp...,499.0,399,20.0,( 18672 ),100.0,Budget
3,Plum BodyLovin' Vanilla Caramello Bestselling ...,495.0,396,20.0,( 13983 ),99.0,Budget
4,Be Bodywise Pigmentation Removal Cream With 2....,649.0,549,15.0,( 3435 ),100.0,Mid-range
...,...,...,...,...,...,...,...
975,Nykaa Wanderlust English Country Rose Floral B...,550.0,358,35.0,( 54055 ),192.0,Mid-range
976,NIVEA Deep Moisture Serum Vit E Body Lotion 48...,760.0,532,30.0,( 63469 ),228.0,Mid-range
977,"Vaseline Sun Protect SPF 30 Body Lotion, Reduc...",870.0,479,45.0,( 17248 ),391.0,Mid-range
978,Cetaphil DailyAdvance Ultra Hydrating Lotion,279.0,240,14.0,( 69661 ),39.0,Budget
979,Plum BodyLovin' Vanilla Caramello Bestselling ...,495.0,396,20.0,( 13983 ),99.0,Budget

In [46]:
new_order = ["ProductName",
    "Brand",
    "Price",
    "SellingPrice",
    "Discount",
    "Savings",
    "PriceCategory",
    "RatingCount"]
df = df[new_order]

In [47]:
df

,ProductName,Brand,Price,SellingPrice,Discount,Savings,PriceCategory,RatingCount
0,Vaseline Gluta-Hya Dewy Radiance Lotion Bright...,Vaseline,380.0,285,25.0,95.0,Budget,22592
1,NIVEA Deep Moisture Serum Vit E Body Lotion 72...,NIVEA,760.0,532,30.0,228.0,Mid-range,63469
2,Wishcare Sunscreen Body Lotion SPF 50 Broad Sp...,Wishcare,499.0,399,20.0,100.0,Budget,18672
3,Plum BodyLovin' Vanilla Caramello Bestselling ...,Plum,495.0,396,20.0,99.0,Budget,13983
4,Nykaa Wanderlust French Lavender Floral Fragra...,Nykaa,550.0,275,50.0,275.0,Mid-range,54055
...,...,...,...,...,...,...,...,...
779,Nykaa Wanderlust English Country Rose Floral B...,Nykaa,550.0,358,35.0,192.0,Mid-range,54055
780,NIVEA Deep Moisture Serum Vit E Body Lotion 48...,NIVEA,760.0,532,30.0,228.0,Mid-range,63469
781,"Vaseline Sun Protect SPF 30 Body Lotion, Reduc...",Vaseline,870.0,479,45.0,391.0,Mid-range,17248
782,Cetaphil DailyAdvance Ultra Hydrating Lotion,Cetaphil,279.0,240,14.0,39.0,Budget,69661
783,Plum BodyLovin' Vanilla Caramello Bestselling ...,Plum,495.0,396,20.0,99.0,Budget,13983

In [48]:
df['Brand'].value_counts().head(50)

Brand
Vaseline     147
NIVEA        147
Plum          98
Nykaa         98
Cetaphil      98
Wishcare      49
Joy           49
MCaffeine     49
Bioderma      49
Name: count, dtype: int64

In [49]:
df=df[df['Brand'].isin(['Vaseline','MCaffeine','Nykaa','Wishcare','Plum','Aveeno','Ponds','Cerave','NIVEA','Cetaphil','Bioderma','Joy','Thriveco'])]

In [50]:
df

,ProductName,Brand,Price,SellingPrice,Discount,Savings,PriceCategory,RatingCount
0,Vaseline Gluta-Hya Dewy Radiance Lotion Bright...,Vaseline,380.0,285,25.0,95.0,Budget,22592
1,NIVEA Deep Moisture Serum Vit E Body Lotion 72...,NIVEA,760.0,532,30.0,228.0,Mid-range,63469
2,Wishcare Sunscreen Body Lotion SPF 50 Broad Sp...,Wishcare,499.0,399,20.0,100.0,Budget,18672
3,Plum BodyLovin' Vanilla Caramello Bestselling ...,Plum,495.0,396,20.0,99.0,Budget,13983
4,Nykaa Wanderlust French Lavender Floral Fragra...,Nykaa,550.0,275,50.0,275.0,Mid-range,54055
...,...,...,...,...,...,...,...,...
779,Nykaa Wanderlust English Country Rose Floral B...,Nykaa,550.0,358,35.0,192.0,Mid-range,54055
780,NIVEA Deep Moisture Serum Vit E Body Lotion 48...,NIVEA,760.0,532,30.0,228.0,Mid-range,63469
781,"Vaseline Sun Protect SPF 30 Body Lotion, Reduc...",Vaseline,870.0,479,45.0,391.0,Mid-range,17248
782,Cetaphil DailyAdvance Ultra Hydrating Lotion,Cetaphil,279.0,240,14.0,39.0,Budget,69661
783,Plum BodyLovin' Vanilla Caramello Bestselling ...,Plum,495.0,396,20.0,99.0,Budget,13983

In [39]:
df["RatingCount"] = df["RatingCount"].str.replace(r"[()]", "", regex=True).str.strip().fillna(0).astype(int)

C:\Users\DELL\AppData\Local\Temp\ipykernel_5324\3076510304.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["RatingCount"] = df["RatingCount"].str.replace(r"[()]", "", regex=True).str.strip().fillna(0).astype(int)

In [51]:
df

,ProductName,Brand,Price,SellingPrice,Discount,Savings,PriceCategory,RatingCount
0,Vaseline Gluta-Hya Dewy Radiance Lotion Bright...,Vaseline,380.0,285,25.0,95.0,Budget,22592
1,NIVEA Deep Moisture Serum Vit E Body Lotion 72...,NIVEA,760.0,532,30.0,228.0,Mid-range,63469
2,Wishcare Sunscreen Body Lotion SPF 50 Broad Sp...,Wishcare,499.0,399,20.0,100.0,Budget,18672
3,Plum BodyLovin' Vanilla Caramello Bestselling ...,Plum,495.0,396,20.0,99.0,Budget,13983
4,Nykaa Wanderlust French Lavender Floral Fragra...,Nykaa,550.0,275,50.0,275.0,Mid-range,54055
...,...,...,...,...,...,...,...,...
779,Nykaa Wanderlust English Country Rose Floral B...,Nykaa,550.0,358,35.0,192.0,Mid-range,54055
780,NIVEA Deep Moisture Serum Vit E Body Lotion 48...,NIVEA,760.0,532,30.0,228.0,Mid-range,63469
781,"Vaseline Sun Protect SPF 30 Body Lotion, Reduc...",Vaseline,870.0,479,45.0,391.0,Mid-range,17248
782,Cetaphil DailyAdvance Ultra Hydrating Lotion,Cetaphil,279.0,240,14.0,39.0,Budget,69661
783,Plum BodyLovin' Vanilla Caramello Bestselling ...,Plum,495.0,396,20.0,99.0,Budget,13983

In [52]:
df.to_csv("BodyLotion.csv", index=False)

In [53]:
df

,ProductName,Brand,Price,SellingPrice,Discount,Savings,PriceCategory,RatingCount
0,Vaseline Gluta-Hya Dewy Radiance Lotion Bright...,Vaseline,380.0,285,25.0,95.0,Budget,22592
1,NIVEA Deep Moisture Serum Vit E Body Lotion 72...,NIVEA,760.0,532,30.0,228.0,Mid-range,63469
2,Wishcare Sunscreen Body Lotion SPF 50 Broad Sp...,Wishcare,499.0,399,20.0,100.0,Budget,18672
3,Plum BodyLovin' Vanilla Caramello Bestselling ...,Plum,495.0,396,20.0,99.0,Budget,13983
4,Nykaa Wanderlust French Lavender Floral Fragra...,Nykaa,550.0,275,50.0,275.0,Mid-range,54055
...,...,...,...,...,...,...,...,...
779,Nykaa Wanderlust English Country Rose Floral B...,Nykaa,550.0,358,35.0,192.0,Mid-range,54055
780,NIVEA Deep Moisture Serum Vit E Body Lotion 48...,NIVEA,760.0,532,30.0,228.0,Mid-range,63469
781,"Vaseline Sun Protect SPF 30 Body Lotion, Reduc...",Vaseline,870.0,479,45.0,391.0,Mid-range,17248
782,Cetaphil DailyAdvance Ultra Hydrating Lotion,Cetaphil,279.0,240,14.0,39.0,Budget,69661
783,Plum BodyLovin' Vanilla Caramello Bestselling ...,Plum,495.0,396,20.0,99.0,Budget,13983

In [54]:
#How many features(Columns) do you have? 
df = pd.read_csv("BodyLotion.csv")
print("Number of columns:", df.shape[1])
print("Column names:", df.columns.tolist())

Number of columns: 8
Column names: ['ProductName', 'Brand', 'Price', 'SellingPrice', 'Discount', 'Savings', 'PriceCategory', 'RatingCount']